"""
Image 1: 7-Day Meal Plan Card
Clean weekly grid with breakfast / lunch / dinner per day
"""
from PIL import Image, ImageDraw, ImageFont
import json, os, textwrap

# ── palette ────────────────────────────────────────────────────────────────
BG        = "#FFFDF7"
HEADER_BG = "#2D6A4F"
ROW_A     = "#F0F7F4"
ROW_B     = "#FFFFFF"
ACCENT    = "#52B788"
TEXT_DARK = "#1B1B1B"
TEXT_MED  = "#3D3D3D"
TEXT_LITE = "#FFFFFF"
COL_HEAD  = "#40916C"

W, H = 1200, 1500

def font(size, bold=False):
    try:
        path = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else \
               "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
        return ImageFont.truetype(path, size)
    except:
        return ImageFont.load_default()

def draw_rounded_rect(draw, xy, radius, fill):
    x1,y1,x2,y2 = xy
    draw.rectangle([x1+radius,y1,x2-radius,y2], fill=fill)
    draw.rectangle([x1,y1+radius,x2,y2-radius], fill=fill)
    draw.ellipse([x1,y1,x1+2*radius,y1+2*radius], fill=fill)
    draw.ellipse([x2-2*radius,y1,x2,y1+2*radius], fill=fill)
    draw.ellipse([x1,y2-2*radius,x1+2*radius,y2], fill=fill)
    draw.ellipse([x2-2*radius,y2-2*radius,x2,y2], fill=fill)

def generate():
    with open("data/weekly_meal_plan.json") as f:
        data = json.load(f)

    plan  = data["plan"]
    month = data["month"]

    img  = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img)

    # Header
    draw.rectangle([0,0,W,110], fill=HEADER_BG)
    draw.text((W//2, 38), "🍽  Parivaar Weekly Meal Plan", font=font(32,True), fill=TEXT_LITE, anchor="mm")
    draw.text((W//2, 82), f"{month} 2025  ·  Delhi NCR  ·  Vegetarian Family", font=font(18), fill="#B7E4C7", anchor="mm")

    # Column headers
    cols = ["Day", "Breakfast", "Lunch", "Dinner", "Protein Add"]
    col_x = [30, 200, 430, 680, 950]
    col_w = [160, 220, 240, 260, 220]

    draw.rectangle([0,110,W,150], fill=COL_HEAD)
    for i, (cx, label) in enumerate(zip(col_x, cols)):
        draw.text((cx + col_w[i]//2, 130), label, font=font(16,True), fill=TEXT_LITE, anchor="mm")

    days = list(plan.keys())
    row_h = 175
    y = 155

    for idx, day in enumerate(days):
        dp   = plan[day]
        bg   = ROW_A if idx % 2 == 0 else ROW_B
        draw.rectangle([0, y, W, y+row_h-4], fill=bg)

        is_weekend = day in ["Saturday","Sunday"]
        day_color  = ACCENT if is_weekend else TEXT_DARK

        # Day pill
        draw_rounded_rect(draw, [col_x[0], y+14, col_x[0]+col_w[0]-10, y+50], 12,
                          ACCENT if is_weekend else "#D8F3DC")
        draw.text((col_x[0]+75, y+32), day, font=font(15,True),
                  fill=TEXT_LITE if is_weekend else "#1B4332", anchor="mm")

        cells = [dp["breakfast"], dp["lunch"], dp["dinner"], dp["protein_add"]]
        emojis = ["☀️", "🥗", "🌙", "💪"]

        for ci, (cx, cw, cell, em) in enumerate(zip(col_x[1:], col_w[1:], cells, emojis)):
            lines = textwrap.wrap(f"{em} {cell}", width=22)
            for li, line in enumerate(lines[:3]):
                draw.text((cx+8, y+20+li*26), line, font=font(15), fill=TEXT_MED)

        y += row_h

    # Footer
    draw.rectangle([0, H-50, W, H], fill=HEADER_BG)
    draw.text((W//2, H-25), "Parivaar Nutrition AI  ·  Generated by GitHub Actions", 
              font=font(14), fill="#B7E4C7", anchor="mm")

    img.save("meal_plan_card.png")
    print("✅ meal_plan_card.png saved")

if __name__ == "__main__":
    generate()
