"""
Image 1: 7-day meal plan card.
Optimized for mobile sharing with larger text and stronger contrast.
"""
from PIL import Image, ImageDraw, ImageFont
import json
import textwrap

BG = "#F6F3EA"
HEADER_BG = "#1F5C45"
HEADER_SUB = "#DCEFE4"
CARD_BG = "#FFFDF8"
CARD_ALT = "#F1F7F1"
CARD_BORDER = "#B7D8C3"
DAY_BG = "#46A36F"
TEXT_DARK = "#153126"
TEXT_MED = "#27473A"
TEXT_LITE = "#FFFFFF"
LABEL = "#2E6A52"

W, H = 1080, 2300


def font(size, bold=False):
    try:
        path = (
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
            if bold
            else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
        )
        return ImageFont.truetype(path, size)
    except Exception:
        return ImageFont.load_default()


def draw_rounded_rect(draw, xy, radius, fill, outline=None, width=1):
    draw.rounded_rectangle(xy, radius=radius, fill=fill, outline=outline, width=width)


def draw_wrapped_block(draw, x, y, label, value, width_chars, value_font, label_font):
    draw.text((x, y), label, font=label_font, fill=LABEL)
    y += 30
    lines = textwrap.wrap(value, width=width_chars)
    for line in lines[:2]:
        draw.text((x, y), line, font=value_font, fill=TEXT_DARK)
        y += 34
    return y


def generate():
    with open("data/weekly_meal_plan.json") as f:
        data = json.load(f)

    plan = data["plan"]
    month = data["month"]

    img = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img)

    draw.rectangle([0, 0, W, 170], fill=HEADER_BG)
    draw.text((W // 2, 58), "Parivaar Weekly Meal Plan", font=font(42, True), fill=TEXT_LITE, anchor="mm")
    draw.text((W // 2, 116), f"{month} | Delhi NCR | Vegetarian Family", font=font(22), fill=HEADER_SUB, anchor="mm")

    y = 205
    outer_x1, outer_x2 = 42, W - 42
    day_pill_w = 220

    for idx, (day, meals) in enumerate(plan.items()):
        card_h = 265
        card_bg = CARD_BG if idx % 2 == 0 else CARD_ALT
        draw_rounded_rect(
            draw,
            [outer_x1, y, outer_x2, y + card_h],
            radius=22,
            fill=card_bg,
            outline=CARD_BORDER,
            width=3,
        )

        draw_rounded_rect(
            draw,
            [outer_x1 + 20, y + 20, outer_x1 + 20 + day_pill_w, y + 78],
            radius=18,
            fill=DAY_BG,
        )
        draw.text(
            (outer_x1 + 20 + day_pill_w // 2, y + 49),
            day,
            font=font(24, True),
            fill=TEXT_LITE,
            anchor="mm",
        )

        left_x = outer_x1 + 28
        right_x = outer_x1 + 535

        draw_wrapped_block(
            draw,
            left_x,
            y + 100,
            "Breakfast",
            meals["breakfast"],
            24,
            font(28, True),
            font(18, True),
        )
        draw_wrapped_block(
            draw,
            left_x,
            y + 178,
            "Lunch",
            meals["lunch"],
            24,
            font(26, True),
            font(18, True),
        )
        draw_wrapped_block(
            draw,
            right_x,
            y + 100,
            "Dinner",
            meals["dinner"],
            24,
            font(28, True),
            font(18, True),
        )
        draw_wrapped_block(
            draw,
            right_x,
            y + 178,
            "Protein Add",
            meals["protein_add"],
            20,
            font(26, True),
            font(18, True),
        )

        y += card_h + 22

    draw.rectangle([0, H - 74, W, H], fill=HEADER_BG)
    draw.text(
        (W // 2, H - 37),
        "Parivaar Nutrition AI | Generated by GitHub Actions",
        font=font(18),
        fill=HEADER_SUB,
        anchor="mm",
    )

    img.save("meal_plan_card.png")
    print("meal_plan_card.png saved")


if __name__ == "__main__":
    generate()
