name: Parivaar Nutrition AI

on:
  workflow_dispatch:

jobs:
  nutrition-report:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pillow
        run: |
          pip install pillow
          
      - name: Generate Meal Plan 
        run: | 
          python scripts/generate_meal_plan.py

      - name: Generate Weekly Meal Plan
        run: |
          python scripts/generate_weekly_plan.py

      - name: Generate Framework
        run: |
          python scripts/generate_framework.py

      - name: Generate Grocery List
        run: |
          python scripts/generate_grocery.py

      - name: Generate Health Mission
        run: |
          python scripts/generate_health.py

      - name: Send Framework
        run: |
          curl -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendPhoto" \
          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -F photo="@weekly_framework.png"
          
      - name: Send Weekly Meal Plan
        run: |
          curl -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendPhoto" \
          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -F photo="@weekly_meal_plan.png"
          

      - name: Send Grocery List
        run: |
          curl -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendPhoto" \
          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -F photo="@grocery_list.png"

      - name: Send Health Mission
        run: |
          curl -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendPhoto" \
          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -F photo="@health_mission.png"
