name: Telegram Test

on:
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Message
        run: |
          curl -X POST "https://api.telegram.org/bot8904770141:AAFsCaFyzvgFvjWtrtKz0vHPz-2gMCJq_RE/sendMessage" \
          -d chat_id="-5251199321" \
          -d text="Hello Varun, GitHub Action is working!"
